apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
  labels:
    id: mypv
spec:
  storageClassName: manual
  capacity:
    storage: 50Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /tmp/k8s-challenge-3
