apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hello
  name: hello
spec:
  containers:
  - image: bonomat/nodejs-hello-world
    name: hello
    ports:
    - name: nodejs-port
      containerPort: 3000
    resources: {}
    readinessProbe:
      initialDelaySeconds: 2
      httpGet:
        path: /
        port: nodejs-port
    livenessProbe:
      initialDelaySeconds: 5
      periodSeconds: 8
      httpGet:
        path: /
        port: nodejs-port    
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
