apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mypod
  name: mypod
spec:
  containers:
  - image: nginx
    name: mypod
    resources:
      requests:
        cpu: 0.5
        memory: 500Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
