apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: cont-1
    image: busybox
    command:
    - sleep
    - "3600"
    volumeMounts:
    - name: vol1
      mountPath: /etc/foo
  - name: cont-2
    image: busybox
    command:
    - sleep
    - "3600"
    volumeMounts:
    - name: vol1
      mountPath: /etc/foo
  terminationGracePeriodSeconds: 2
  volumes:
  - name: vol1
    emptyDir: {}    