apiVersion: v1
kind: Pod
metadata:
  name: mypod1
spec:
  nodeName: minikube
  containers:
  - name: busybox
    image: busybox
    command:
    - sleep
    - "3600"
    volumeMounts:
    - name: vol1
      mountPath: /etc/foo
  volumes:
  - name: vol1
    persistentVolumeClaim:
      claimName: mypvc