apiVersion: v1
kind: Pod
metadata:
  name: business-app
spec:
  terminationGracePeriodSeconds: 2
  initContainers:
  - name: configurer
    image: busybox
    command:
    - wget
    - "-qO"
    - "/usr/shared/app/config.json"
    - https://raw.githubusercontent.com/bmuschko/ckad-crash-course/master/exercises/03-init-container/app/config/config.json
    volumeMounts:
    - name: vol1
      mountPath: /usr/shared/app
  containers:
  - name: web
    image: bmuschko/nodejs-read-config:1.0.0
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: vol1
      mountPath: /usr/shared/app
  volumes:
  - name: vol1
    emptyDir: {}  