apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hello-world
  name: hello-world
spec:
  volumes:
  - name: vol1
    emptyDir: {}
  containers:
  - image: bmuschko/nodejs-hello-world:1.0.0
    imagePullPolicy: IfNotPresent
    name: hello-world
    ports:
    - containerPort: 3000
    resources:
      limits:
        ephemeral-storage: 2Gi
        memory: 500Mi
      requests:
        cpu: 100m
        ephemeral-storage: 1Gi
        memory: 500Mi
    volumeMounts:
    - name: vol1
      mountPath: /var/log    
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
