apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multic2
  name: multic2
spec:
  containers:
  - args:
    - sh
    - -c
    - while true; do echo "Hi I am from Main container" >> /var/log/index.html; sleep 5; done
    image: busybox
    name: busybox
    resources: {}
    volumeMounts:
    - mountPath: /var/log
      name: web
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: web
    ports:
      - name: web-port
        containerPort: 80
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: web
    emptyDir: {}
status: {}
