apiVersion: v1
kind: Pod
metadata:
  labels:
    run: bash
  name: bash
spec:
  securityContext:
    runAsUser: 21
  volumes:
    - name: share
      emptyDir: {}
  initContainers:
  - name: init
    image: bash
    command:
    - /bin/sh
    - -c
    - chmod og-w -R /tmp/share
    volumeMounts:
    - name: share
      mountPath: /tmp/share
    securityContext:
      runAsUser: 0  
  containers:
  - command:
    - /bin/sh
    - -c
    - sleep 1d
    image: bash
    name: bash1
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - name: share
        mountPath: /tmp/share
    securityContext:
      runAsUser: 0    
  - command:
    - /bin/sh
    - -c
    - sleep 1d
    image: bash
    name: bash2
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - name: share
        mountPath: /tmp/share
  restartPolicy: Never
  terminationGracePeriodSeconds: 2