apiVersion: v1
kind: Pod
metadata:  
  name: testpod
spec:
  volumes:
  - name: share
    emptyDir: {}
  containers:
  - command:
    - /bin/sh
    - -c
    - sleep 1d
    image: bash
    name: bash
    imagePullPolicy: IfNotPresent
    securityContext:
      runAsUser: 1001
    volumeMounts:
    - name: share
      mountPath: /tmp/share  # always mounted as root with full permission for everyone
  restartPolicy: Never
  terminationGracePeriodSeconds: 2