apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rnd-rb
  namespace: rnd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rnd-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: rnd