apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod1
  name: pod1
spec:
  containers:
  - image: nginx
    name: pod1
    resources: {}
    envFrom:
    - configMapRef:
        name: cfgfromfile
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
