apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod10
  name: pod10
spec:
  containers:
  - image: nginx
    name: pod10
    resources: {}
    env:
        - name: mynvkeys
          valueFrom:
            configMapKeyRef:
              name: cfgfromfilerenamed
              key: mynvkeys
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
