apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod3
  name: pod3
spec:
  containers:
  - image: nginx
    name: pod3
    resources: {}
    volumeMounts:
      - name: vol
        mountPath: /etc/config
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: vol
      configMap:
        name: cfgfromfile
status: {}
