apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod4
  name: pod4
spec:
  containers:
  - image: nginx
    name: pod4
    resources: {}
    volumeMounts:
      - name: vol
        mountPath: /etc/config
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: vol
    configMap:
      name: cfgfromfile
      items:
      - key: indoor
        path: indoor
status: {}
