apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod9
  name: pod9
spec:
  containers:
  - image: nginx
    name: pod9
    resources: {}
    envFrom:
        - configMapRef:
            name: cfgfromfilerenamed
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
