apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ch5p02subtask1
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/phone"
        backend:
          service:
            name: phone
            port:
              number: 80
      - pathType: Prefix
        path: "/tablet"
        backend:
          service:
            name: tablet
            port:
              number: 80