apiVersion: v1
kind: Pod
metadata:
  name: tablet
  labels:
    app: tablet
spec:
  terminationGracePeriodSeconds: 2
  restartPolicy: Always
  initContainers:
  - name: init
    image: busybox
    imagePullPolicy: IfNotPresent  
    command:
    - /bin/sh
    - -c
    - echo Hello from $HOSTNAME > /data/index.html
    volumeMounts:
    - name: vol1
      mountPath: /data
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent  
    ports:
    - containerPort: 80
    volumeMounts:
    - name: vol1
      mountPath: /usr/share/nginx/html
  volumes:
  - name: vol1
    emptyDir: {}
