apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
  labels:
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: v1
  template:
    metadata:
      labels:
        app: v1
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
      terminationGracePeriodSeconds: 2          
  