apiVersion: v1
kind: Pod
metadata:
  name: adapter
spec:
  volumes:
  - name: vol1
    emptyDir: {}
  containers:
  - name: app
    image: busybox
    command:
    - sh
    - -c
    - |
      while true; do
        echo "$(date) | $(du -sh ~)" >> /var/logs/diskspace.txt;
        sleep 5;
      done
    volumeMounts:
    - name: vol1
      mountPath: /var/logs  
  - name: transformer
    image: busybox
    command:
    - sh
    - -c
    - |
      sleep 20;
      while true; do
        while read LINE; do
          echo "$LINE" | cut -f2 -d"|" >> $(date +%Y-%m-%d-%H-%M-%S)-transformed.txt;
        done < /var/logs/diskspace.txt;
        sleep 20; 
      done;
    volumeMounts:
    - name: vol1
      mountPath: /var/logs            