apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  storageClassName: ""
  capacity:
    storage: 4Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/mnt/data"

--- 
# As long as the storageClassName and accessModes match, and the resource request size 
# is within the capacity of a PV, the PVC will automatically be bound with the matched PV
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  storageClassName: "" 
  accessModes:
    - ReadWriteOnce
  # volumeName: mypv  # this specifically binds to a PV as long as the criteria match e.g. accessModes, size and SC.
  volumeMode: Filesystem
  resources:
    requests:
      storage: 3Mi # this is to be within the capacity of the PV

# --- 
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pv0003
# spec:
#   storageClassName: ""
#   capacity:
#     storage: 8Mi
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   claimRef:
#     namespace: default # This is super important to mention, without this binding does not work!!!!
#     name: myclaim
#   hostPath:
#     path: "/mnt/data"
# ---

#  kind: PersistentVolumeClaim
#  apiVersion: v1
#  metadata:
#    name: myclaim
#  spec:
#    storageClassName: ""
#    accessModes:
#      - ReadWriteOnce
#    resources:
#      requests:
#        storage:  8Mi