apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: backend
  name: backend
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: backend
    resources: {}
    envFrom:
    - configMapRef:
        name: db-config
    env:
    - name: DB_PASSWORD
      valueFrom:    
        secretKeyRef:
          name: db-credentials
          key: db-password
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
