apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test
  name: test
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: test
    resources: 
      requests:
        cpu: 1
        memory: 100Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
