apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: backend
  name: backend
spec:
  serviceAccountName: backend-team
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: backend
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
