apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod1
  name: pod1
spec:
  containers:
  - args:
    - sleep
    - infinity
    image: bash
    name: pod1
    resources: {}
    envFrom:
    - configMapRef:
        name: mycm
    volumeMounts:
    - name: secv
      mountPath: /tmp/secret1
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
  - name: secv
    secret:
      secretName: secret1
status: {}
