apiVersion: v1
kind: Pod
metadata:  
  labels:
    run: mypod
  name: mypod
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: nginx
    envFrom:
    - secretRef:
        name: mysec
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  terminationGracePeriodSeconds: 2
status: {}
