apiVersion: v1
kind: Pod
metadata:
  labels:
    run: redis
  name: redis
  namespace: ch2p02
spec:
  volumes:
  - name: cache-volume
    emptyDir: {}
  containers:
  - image: redis
    name: redis
    volumeMounts:
    - mountPath: /data
      name: cache-volume
  dnsPolicy: ClusterFirst
  restartPolicy: Always
