apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: service-list
  name: service-list
spec:
  serviceAccountName: api-call
  terminationGracePeriodSeconds: 2
  containers:
  - image: alpine/curl:3.14
    name: service-list
    command: ["sh", "-c"]
    args:
    - 'TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token); 
      while true; do curl -ksm 2 -H "Authorization: Bearer $TOKEN" 
      https://kubernetes.default/api/v1/namespaces/default/services; sleep 2; done;'
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
