apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: netpol6
  namespace: ch5p01-secured
spec:
  podSelector:
    matchLabels:
      tag: subtask6
  policyTypes:
    - Ingress
  ingress:
    - from:
         # from any pod with "globaltrust" tag, or any pod from "ch5p01-exttrust" namespace
        - podSelector:
            matchLabels:
              tag: globaltrust
          namespaceSelector: {}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ch5p01-exttrust
        
      
