apiVersion: v1
kind: Pod
metadata:
  name: hello-world
spec:
  terminationGracePeriodSeconds: 2
  containers:
  - name: hello-world
    image: bmuschko/nodejs-hello-world:1.0.0
    imagePullPolicy: IfNotPresent
    ports:
    - name: web
      containerPort: {{ .Values.container_port }}